In [1]:
import xarray as xr
import numpy as np
from PIL import Image as PILImage
from osgeo import gdal, osr, gdal_array
import netCDF4
url = 'cloud3D_image.nc'
nc = netCDF4.Dataset(url)
data = nc.variables
print (data.keys())

odict_keys(['band_0', 'nb_views', 'nodata', 'radius', 'secondary_1', 'secondary_2', 'dir_view_1_vector', 'dir_view_1_origin', 'dir_view_2_vector', 'dir_view_2_origin', 'dir_view_3_vector', 'dir_view_3_origin', 'coord_ECEF'])


In [2]:
data

OrderedDict([('band_0', <class 'netCDF4._netCDF4.Variable'>
              int32 band_0(i, j)
              unlimited dimensions: 
              current shape = (500, 500)
              filling on, default _FillValue of -2147483647 used),
             ('nb_views', <class 'netCDF4._netCDF4.Variable'>
              int32 nb_views(i, j)
              unlimited dimensions: 
              current shape = (500, 500)
              filling on, default _FillValue of -2147483647 used),
             ('nodata', <class 'netCDF4._netCDF4.Variable'>
              int32 nodata(i, j)
              unlimited dimensions: 
              current shape = (500, 500)
              filling on, default _FillValue of -2147483647 used),
             ('radius', <class 'netCDF4._netCDF4.Variable'>
              float32 radius(i, j)
              unlimited dimensions: 
              current shape = (500, 500)
              filling on, default _FillValue of 9.969209968386869e+36 used),
             ('secondary_1', <cl

In [28]:
cloud3D = np.array(nc.variables['coord_ECEF'])

On récupère la position (x,y,z) pour chaque point de l'image:

In [29]:
cloud3D

array([[[-4127572., -4127572., -4127572., ..., -4127714., -4127714.,
         -4127714.],
        [       0., -4127572., -4127572., ..., -4127714., -4127714.,
         -4127714.],
        [       0., -4127571., -4127571., ..., -4127713., -4127714.,
         -4127714.],
        ...,
        [-4127448., -4127449., -4127449., ..., -4127587., -4127587.,
         -4127587.],
        [-4127448., -4127448., -4127448., ..., -4127587., -4127587.,
         -4127587.],
        [-4127448., -4127448., -4127447., ..., -4127586., -4127586.,
         -4127588.]],

       [[ 2907190.,  2907189.,  2907189., ...,  2906982.,  2906981.,
          2906981.],
        [       0.,  2907189.,  2907188., ...,  2906982.,  2906981.,
          2906980.],
        [       0.,  2907189.,  2907188., ...,  2906981.,  2906981.,
          2906980.],
        ...,
        [ 2907103.,  2907103.,  2907102., ...,  2906893.,  2906892.,
          2906892.],
        [ 2907103.,  2907102.,  2907102., ...,  2906892.,  2906892.,
   

On utilise des classes par l'algorithme  Kmeans par défaut de OTB

In [30]:
classe = gdal.Open('KMeansClassification.tif')
band = classe.GetRasterBand(1)
arr = band.ReadAsArray()
print (arr)
print ("nombre de classe est égale à " + str(np.max(arr)+1))

[[4 4 4 ... 4 4 4]
 [4 4 4 ... 4 4 4]
 [4 4 4 ... 4 4 4]
 ...
 [3 0 0 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 [0 2 2 ... 0 0 0]]
nombre de classe est égale à 5


A voir 0,1,2,3,4 correspond à quelle classe???

Ici, pour chaque pixel de l'image, on a sa position 3D et sa classe. 